name: Nebula Production Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to production server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: nebulastudentportal.slt.lk
          username: cpo_admin
          port: 2002
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/nebula
            ./deploy.sh
